title: "Eclipse IoT Packages™"
copyright: "Copyright © Eclipse Foundation, Inc. All Rights Reserved."

url: https://eclipse.org

baseurl: /packages
permalink: pretty

plugins:
  - jekyll-contentblocks

collections:
  packages:
    output: true
  questions:
    output: false
